src/robot_project/robot_app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import views

app_name = 'robot_app'

urlpatterns = [
    path('', views.indexfunc, name='index'),
    path('detail/<int:pk>/', views.detailfunc, name='detail'),
    path('update/<int:pk>/', views.updatefunc, name='update'),
    path('signup/', views.signupfunc, name='signup'),
    path('login/', views.loginfunc, name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('g_navi/', views.g_navi, name='g_navi'),
    path('youtube/', views.youtube, name='youtube'),
    path('add_questions/', views.add_questions, name='add_questions'),
    path('morning/', views.morning, name='morning'),
    path('morning/edit/<int:pk>/', views.morning_edit, name='morning_edit'),
    path('blog_create/', views.blog_create, name='blog_create'),
    path('news/', views.news, name='news'),
    path('mycalendar/', views.MyCalendar.as_view(), name='month'),
    path('month/<int:year>/<int:month>/', views.MonthCalendar.as_view(), name='month'),
    path('mycalendar/', views.MyCalendar.as_view(), name='mycalendar'),
    path('mycalendar/<int:year>/<int:month>/<int:day>/', views.MyCalendar.as_view(), name='mycalendar'),
    path('month_with_schedule/', views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('month_with_schedule/<int:year>/<int:month>/', views.MonthWithScheduleCalendar.as_view(), name='month_with_schedule'),
    path('net_shop/', views.net_shop, name='net_shop'),
    path('shop_detail/<str:itemId>/', views.shop_detail, name='shop_detail'),
    path('map/', views.map, name='map'),
    path('robot_review/', views.robot_review, name='robot_review'),
    path('notify/', views.notify, name='notify'),
    path('week_tenki/', views.week_tenki, name='week_tenki'),
    path('any_questions/', views.any_questions, name='any_questions'),
    path('ajax_answer_add/', views.ajax_answer_add, name='ajax_answer_add'),
]

src/robot_project/robot_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('robot_app.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/robot_project/robot_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
from django.db import models
from django.utils import timezone


class User_Question(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    question = models.CharField(max_length=50, blank=True, null=True)
    answer = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.question


class GNAVI_Question(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    question = models.CharField(max_length=50, blank=True, null=True)
    answer = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.question


class Youtube_Question(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    question = models.CharField(max_length=50, blank=True, null=True)
    answer = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.question


SCORE_CHOICES = [
    (1, '★'),
    (2, '★★'),
    (3, '★★★'),
    (4, '★★★★'),
    (5, '★★★★★'),
]
class Robot_Evaluation(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    robot_name = models.CharField('robot_name', max_length=50, blank=True, null=True)
    score = models.PositiveSmallIntegerField(verbose_name='ロボットスコア', choices=SCORE_CHOICES, default='3')

    #ユーザーが同じロボットに2つ以上レビューを書けない設定
    # class Meta:
    #     unique_together = ('robot_name', 'user_name')

    def __str__(self):
        return str(self.robot_name)


class Blog(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    text = models.CharField(max_length=150, blank=True, null=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)
    updated_at = models.DateTimeField('更新日', default=timezone.now)

    def __str__(self):
        return str(self.title)


class News(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    question = models.CharField(max_length=50, blank=True, null=True)
    answer = models.CharField(max_length=50, blank=True, null=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)
    updated_at = models.DateTimeField('更新日', default=timezone.now)

    def __str__(self):
        return self.question


class Schedule(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    summary = models.CharField('タイトル', max_length=50)
    description = models.TextField('メモ', blank=True)
    start_time = models.TimeField('開始時間', default=datetime.time(7,0,0))
    end_time = models.TimeField('終了時間', default=datetime.time(8,0,0))
    date = models.DateField('日付')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.summary


class Net_Shop(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    question = models.CharField(max_length=50, blank=True, null=True)
    answer = models.CharField(max_length=50, blank=True, null=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)
    updated_at = models.DateTimeField('更新日', default=timezone.now)

    def __str__(self):
        return self.question


class ChatBot(models.Model):
    user_name = models.ForeignKey('users.User', on_delete=models.CASCADE, blank=True, null=True)
    question = models.CharField('質問', max_length=255, blank=True, null=True)
    answer = models.CharField('回答', max_length=255, blank=True, null=True)

    def __str__(self):
        return self.question

src/robot_project/users/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.core.mail import send_mail
from django.utils import timezone

from django.contrib.auth.base_user import BaseUserManager


class UserManager(BaseUserManager):
    """カスタムユーザーマネージャー"""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        # email を必須にする
        if not email:
            raise ValueError('The given email must be set')
        # email で User モデルを作成
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル"""

    email = models.EmailField("メールアドレス", unique=True, null=True, blank=True)
    profname = models.CharField("ユーザーネーム", max_length=20, null=True, blank=True, unique=True)
    icon = models.ImageField(upload_to="image/", null=True, blank=True)
    proftext = models.CharField("プロフィール", max_length=300, null=True, blank=True)
    is_staff = models.BooleanField("is_staff", default=False)
    is_active = models.BooleanField("is_active", default=True)
    date_joined = models.DateTimeField("date_joined", default=timezone.now)

    objects = UserManager()

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"

src/robot_project/robot_app/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from .models import Schedule
from .models import User_Question

class SignUpForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class EditForm(forms.ModelForm):
    class Meta:
        model = User_Question
        fields = '__all__'


class ScheduleForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ('date', 'summary', 'description', 'start_time', 'end_time')
        widgets = {
            'date': forms.TextInput(attrs={
                'autocomplete': 'off',
                'class': 'form-control',
            }),
            'summary': forms.TextInput(attrs={
                'autocomplete': 'off',
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'autocomplete': 'off',
                'class': 'form-control',
            }),
            'start_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'end_time': forms.TextInput(attrs={
                'class': 'form-control',
            }),
        }

    def clean_end_time(self):
        start_time = self.cleaned_data['start_time']
        end_time = self.cleaned_data['end_time']
        if end_time <= start_time:
            raise forms.ValidationError(
                '終了時間は、開始時間よりも後にしてください'
            )
        return end_time

src/robot_project/robot_app/views/mixins.py
import calendar
import datetime
from collections import deque
import itertools



class BaseCalendarMixin():
    """基底クラス"""
    first_weekday = 0
    week_name = ['月', '火', '水', '木', '金', '土', '日']

    def setup_calendar(self):
        self._calendar = calendar.Calendar(self.first_weekday)


    def get_week_names(self):
        week_names = deque(self.week_names)
        week_names.rotate(-self.first_weekday)
        return week_names


class MonthCalendarMixin(BaseCalendarMixin):

    #前月
    def get_previous_month(self, date):
        if date.month == 1:
            return date.replace(year=date.year-1, month=12, day=1)
        else:
            return date.replace(month=date.month-1, day=1)

    # 次月
    def get_next_month(self, date):
        if date.month == 12:
            return date.replace(year=date.year+1, month=1, day=1)
        else:
            return date.replace(month=date.month+1, day=1)

    def get_month_days(self, date):
        return self._calendar.monthdatescalendar(date.year, date.month)

    #現在
    def get_current_month(self):
        month = self.kwargs.get('month')
        year = self.kwargs.get('year')
        if month and year:
            month = datetime.date(year=int(year), month=int(month), day=1)
        else:
            month = datetime.date.today().replace(day=1)
        return month

    def get_month_calendar(self):
        self.setup_calendar()
        current_month = self.get_current_month()
        calendar_data = {
            'now': datetime.date.today(),
            'month_days': self.get_month_days(current_month),
            'month_current': current_month,
            'month_previous': self.get_previous_month(current_month),
            'month_next': self.get_next_month(current_month),
        }
        return calendar_data


class MonthWithScheduleMixin(MonthCalendarMixin):
    """スケジュール付きの、月間カレンダーを提供するMixin"""

    def get_month_schedules(self, start, end, days):
        """それぞれの日とスケジュールを返す"""
        lookup = {
            # '例えば、date__range: (1日, 31日)'を動的に作る
            '{}__range'.format(self.date_field): (start, end)
        }
        # 例えば、Schedule.objects.filter(date__range=(1日, 31日)) になる
        queryset = self.model.objects.filter(**lookup)

        # {1日のdatetime: 1日のスケジュール全て, 2日のdatetime: 2日の全て...}のような辞書を作る
        day_schedules = {day: [] for week in days for day in week}
        for schedule in queryset:
            schedule_date = getattr(schedule, self.date_field)
            day_schedules[schedule_date].append(schedule)

        # day_schedules辞書を、周毎に分割する。[{1日: 1日のスケジュール...}, {8日: 8日のスケジュール...}, ...]
        # 7個ずつ取り出して分割しています。
        size = len(day_schedules)
        return [{key: day_schedules[key] for key in itertools.islice(day_schedules, i, i+7)} for i in range(0, size, 7)]

    def get_month_calendar(self):
        calendar_context = super().get_month_calendar()
        month_days = calendar_context['month_days']
        month_first = month_days[0][0]
        month_last = month_days[-1][-1]
        calendar_context['month_day_schedules'] = self.get_month_schedules(
            month_first,
            month_last,
            month_days
        )
        return calendar_context

src/robot_project/templates/robot_app/add_questions.html
{% extends 'robot_app/base.html' %}
{% load static %}

{% block customcss %}
<link href="{% static 'robot_app/index.css' %}" rel="stylesheet">
{% endblock customcss %}

{% block title %}追加の質問{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="question_robot">
        <img src="/media/robot2.png" width="50">
    </div>

    <div class="question_form">
        <form method="POST" action="" name="form1">{% csrf_token %}
            <p class="tgt">{{ mesg }}</p>
            {% if type == "cleanliness" or type == "mycar" %}
                {{ number }}
            {% endif %}
            {% if type == "car_brand" %}
            <p>{{ car_brand }}</p>
            {% endif %}
            {% if type != "thanks" and type != "no_question" %}
                <input type="hidden" name="question" value="{{ type }}">
                <input type="text" id="id_question" name="answer" class="form-control" autocomplete="off">
            {% else %}
                <script>
                    window.location.href = 'http://localhost:8080/';
                </script>
            {% endif %}
        </form>
    </div>

    <div class="result">

    </div>

</div>




<script>
    var id = $('form').attr('id');
    // 上記の入力欄にフォーカスを与える
    document.getElementById(id).focus();
</script>

<script>
$(window).on('load',function(){
    // ここから文字を<span></span>で囲む記述
    $('.typ').children().andSelf().contents().each(function() {
        if (this.nodeType == 3) {
            $(this).replaceWith($(this).text().replace(/(\S)/g, '<span>$1</span>'));
        }
    });
    // ここから一文字ずつフェードインさせる記述
    $('.typ').css({'opacity':1});
    for (var i = 0; i <= $('.typ').children().size(); i++) {
        $('.typ').children('span:eq('+i+')').delay(50*i).animate({'opacity':1},50);
    };
});
</script>

{% endblock content %}

src/robot_project/templates/robot_app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'robot_app/index.css' %}">

    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/ui-lightness/jquery-ui.css"/>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>

    {% block customcss %}
    {% endblock customcss %}

    <title>{% block title %}スマホ専用ロボット{% endblock title %}</title>
  </head>
  <body onLoad="document.form1.answer.focus()" style="background-color: #F2F2F2;">


 <!-- Central Modal Medium Success -->
 <div class="modal fade left" id="centralModalSuccess" tabindex="-1" role="dialog" aria-labelledby="centralModalSuccess"
   aria-hidden="true">
   <div class="mypage modal-dialog modal-notify modal-success" role="document">
     <!--Content-->
     <div class="modal-content">
       <!--Header-->
       <div class="modal-header">
         <p class="heading lead">My Profile</p>

         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true" class="white-text">&times;</span>
         </button>
       </div>

       <!--Body-->
       <div class="modal-body">
         <div class="intro_list">
           <ul>
             <li><i class="fas fa-user-circle"></i>プロフィール</li>
             <li><i class="fas fa-list"></i>リスト</li>
             <li><i class="far fa-comment-dots"></i>トピック</li>
             <li><i class="far fa-bookmark"></i>ブックマーク </li>
           </ul>
         </div>
       </div>
     </div>
   </div>
 </div>
 <!-- Central Modal Medium Success-->


    <header class="header_bg clearfix">
        <div class="header_class clearfix">
            <div class="header_menu">
                <div class="robot_icon">
                    <a href="/" data-toggle="modal" data-target="#centralModalSuccess">
                        <i class="fas fa-bars"></i>
                    </a>
                </div>
                <div class="user_icon">
                    <i class="far fa-bell" aria-hidden="true" data-toggle="modal" data-target="#frameModalBottom"></i>
                </div>
            </div>

             <!-- Central Modal Medium Success -->
             <div class="modal fade right" id="frameModalBottom" tabindex="-1" role="dialog" aria-labelledby="centralModalSuccess"
               aria-hidden="true">
               <div class="loginpage modal-dialog modal-notify modal-success" role="document">
                 <!--Content-->
                 <div class="modal-content">
                   <!--Header-->
                   <div class="modal-header">
                     <p class="heading lead">
                       {% if user.is_authenticated %}
                         <a href="{% url 'robot_app:detail' user.id %}">{{ user.profname }}</a>でログイン中
                       {% else %}
                         Sign in
                       {% endif %}
                     </p>


                     <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                       <span aria-hidden="true" class="white-text">&times;</span>
                     </button>
                   </div>

                   <!--Body-->
                   <div class="modal-body">
                     <div class="intro_list">
                       <ul>
                         {% if user.is_authenticated %}
                            {% if notify_count != 0 %}
                              <li><i class="fas fa-bell"></i><a href="{% url 'robot_app:notify' %}">通知が届いています</a></li>
                            {% endif %}
                           <li><i class="fas fa-user-circle"></i><a href="{% url 'robot_app:detail' user.id %}">マイページ</a></li>
                           <li><i class="fas fa-sign-out-alt"></i><a href="{% url 'robot_app:logout' %}">ログアウト</a></li>
                         {% else %}
                           <li><i class="fas fa-sign-in-alt"></i><a href="{% url 'robot_app:signup' %}">新規登録</a></li>
                           <li><i class="far fa-arrow-alt-circle-right"></i><a href="{% url 'robot_app:login' %}">ログイン</a></li>
                         {% endif %}
                       </ul>
                     </div>
                   </div>
                 </div>
               </div>
             </div>
              </div>
            </div>
        </div>
    </header>
  {% block header %}

  {% endblock header %}

    {% block content %}
    <div class="container">

    </div>
    {% endblock content %}


  <footer class="footer">
    <nav class="global-nav">
      <ul class="nav-list">
        <li class="nav-item">
          <a href="/">
            <i class="fas fa-home"></i>
            <span>Home</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="/robot_review">
            <i class="fas fa-star"></i>
            <span>Star</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="/notify">
            <i class="far fa-comment-dots"><span class="notify" style="display: inline; position: relative; top: -16px; color:#FF4D5B; font-weight: 600; margin: -6px;">
              {{ notify_count }}</span></i>
            <span>Notify</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="/map">
            <i class="fas fa-globe-asia"></i>
            <span>Map</span>
          </a>
        </li>

      </ul>
    </nav>
  </footer>



  <!-- 文字がふるアニメーション-->
   <script>
    $(window).bind('load',function(){
      // ここで文字を<span></span>で囲む
      $('.tgt').children().andSelf().contents().each(function() {
        if (this.nodeType == 3) {
          $(this).replaceWith($(this).text().replace(/(\S)/g, '<span>$1</span>'));
        }
      });
      // 一文字ずつフェードインさせる
      $('.tgt').css({'opacity':1});
      for (var i = 0; i <= $('.tgt').children().size(); i++) {
          $('.tgt').children('span:eq('+i+')').delay(50*i).animate({'opacity':1},50);
        };
      });
   </script>

 <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>


{% block extrajs %}{% endblock %}
  </body>
</html>

src/robot_project/templates/robot_app/index.html
{% extends 'robot_app/base.html' %}
{% load static %}

{% block customcss %}
<link href="{% static 'robot_app/index.css' %}" rel="stylesheet">
{% endblock customcss %}

{% block title %}ロボット{% endblock title %}

{% block content %}
    {% if messages %}
        <div class="messages_ul">
            <ul>
            {% for message in messages %}
                <li class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</li>
            {% endfor %}
            </ul>
        </div>
    {% endif %}


    <div class="container mt-5 pc_display">
        <div class="question_robot">
            <img src="/media/robot2.png">
        </div>
        <div class="question_form">
            <form method="POST" action="" name="form1">{% csrf_token %}
                <p class="tgt">{{ mesg }}</p>
                {% if type == "thanks" %}
                    {{ thanks }}
                {% endif %}
                {% if type != "thanks" %}
                <input type="hidden" name="question" value="{{ type }}">
                <input type="text" id="id_answer" name="answer" class="form-control" autocomplete="off">
                {% else %}
                <script>
                    window.location.href = 'http://localhost:8080/';
                </script>
                {% endif %}
            </form>
        </div>
        <!-- ログインしていない場合 from-->
        {% if user.is_anonymous %}
            新規登録かログインをしてください
        {% endif %}

    </div>



<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>


<script>
    var id = $('form').attr('id');
    // 上記の入力欄にフォーカスを与える
    document.getElementById(id).focus();
</script>


<script>
$(window).on('load',function(){
    // ここから文字を<span></span>で囲む記述
    $('.typ').children().andSelf().contents().each(function() {
        if (this.nodeType == 3) {
            $(this).replaceWith($(this).text().replace(/(\S)/g, '<span>$1</span>'));
        }
    });
    // ここから一文字ずつフェードインさせる記述
    $('.typ').css({'opacity':1});
    for (var i = 0; i <= $('.typ').children().size(); i++) {
        $('.typ').children('span:eq('+i+')').delay(50*i).animate({'opacity':1},50);
    };
});
</script>

{% endblock content %}

src/robot_project/templates/robot_app/month.html
{% extends 'robot_app/base.html' %}
{% load static %}

{% block customcss %}
<link href="{% static 'robot_app/calender.css' %}" rel="stylesheet">
{% endblock customcss %}

{% block title %}カレンダー{% endblock title %}

{% block content %}
    <a href="{% url 'robot_app:month' month_previous.year month_previous.month %}">前月</a>
    {{ month_current | date:"Y年m月" }}
    <a href="{% url 'robot_app:month' month_next.year month_next.month %}">次月</a>

    <table class="table">
        <thead>
        <tr>
            {% for w in week_names %}
                <th>{{ w }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tbody>
        {% for week in month_days %}
            <tr>
                {% for day in week %}
                    {% if now == day %}
                        <td class="table-success">
                            {% else %}
                        <td>
                    {% endif %}

                {% if month_current.month != day.month %}
                    {{ day | date:"m/d" }}
                {% else %}
                    {{ day.day }}
                {% endif %}

                </td>
                {% endfor %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}